# SPDX-FileCopyrightText: 2020 The cython-sgio Authors
#
# SPDX-License-Identifier: MIT

dist: xenial

language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9-dev

script:
  - pip install .[dev]
